# The `User` entity from docs/02-data-model.md, minus auth credentials (owned by Supabase
# Auth — see docs/18-backend-build-plan.md). `id` is a FK to auth.users.id, assigned at
# sign-up via a DB trigger in the real Supabase database, not generated by Rails.
class Profile < ApplicationRecord
  self.primary_key = "id"

  belongs_to :city, foreign_key: :location_city_id, inverse_of: :profiles, optional: true
  has_many :posts, class_name: "Post", foreign_key: :user_id, inverse_of: :author
  has_many :group_memberships, foreign_key: :user_id, inverse_of: :user
  has_many :groups, through: :group_memberships

  validates :username, presence: true, uniqueness: true

  # Rank Tiers, per docs/02-data-model.md — derived from points, never stored independently.
  RANK_TIERS = [
    [0..19, "Cub"],
    [20..49, "Scout"],
    [50..149, "Rider"],
    [150..349, "Alpha"],
    [350..Float::INFINITY, "Pedal Monster"]
  ].freeze

  def rank
    RANK_TIERS.find { |range, _tier| range.cover?(points) }&.last
  end
end
